import 'package:flutter/material.dart';
import 'package:mega_one_app/feature/model/modelStyle.dart';

final List<ModelStyle> list = [
  ModelStyle(color: Colors.red, text: 'A'),
  ModelStyle(color: Colors.green, text: 'B'),
  ModelStyle(color: Colors.blue, text: 'C'),
  ModelStyle(color: Colors.pink, text: 'D'),
  ModelStyle(color: Colors.orange, text: 'E'),
  ModelStyle(color: Colors.yellow, text: 'F'),
  ModelStyle(color: Colors.greenAccent, text: 'G'),
  ModelStyle(color: Colors.blueGrey, text: 'H'),
  ModelStyle(color: Colors.blueAccent, text: 'I'),
  ModelStyle(color: Colors.pink, text: 'J'),
  ModelStyle(color: Colors.deepOrange, text: 'K'),
  ModelStyle(color: Colors.deepPurple, text: 'L'),
  ModelStyle(color: Colors.amber, text: 'M'),
  ModelStyle(color: Colors.teal, text: 'N'),
  ModelStyle(color: Colors.limeAccent, text: 'O'),
  ModelStyle(color: Colors.cyan, text: 'P'),
  ModelStyle(color: Colors.orangeAccent, text: 'Q'),
  ModelStyle(color: Colors.pinkAccent, text: 'R'),
  ModelStyle(color: Colors.lightGreen, text: 'S'),
  ModelStyle(color: Colors.red, text: 'T'),
  ModelStyle(color: Colors.yellowAccent, text: 'U'),
  ModelStyle(color: Colors.lightBlueAccent, text: 'V'),
  ModelStyle(color: Colors.blue, text: 'W'),
  ModelStyle(color: Colors.purpleAccent, text: 'X'),
  ModelStyle(color: Colors.orangeAccent, text: 'Y'),
  ModelStyle(color: Colors.yellowAccent, text: 'Z'),
  ModelStyle(color: Colors.redAccent, text: '1'),
  ModelStyle(color: Colors.lime, text: '2'),
  ModelStyle(color: Colors.limeAccent, text: '3'),
  ModelStyle(color: Colors.deepOrangeAccent, text: '4'),
  ModelStyle(color: Colors.blue, text: '5'),
];
